server:
  port: 80
  
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1/s2-damai?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver
     
# 邮件发送  Yml 配置规则: 如果某个阶段有重复配置情况, 必要要合并
  mail:
      # 邮箱服务器地址
      host: smtp.qq.com
      # 用户名
      username: 1953745128@qq.com
      # 密码 
      password: gpaxrxvhqmdwdbii
      default-encoding: UTF-8

     
logging:
  level:
    com:
      yc:
        S3SpringBoot:
          dao: debug
          web: warn
          
mail:
   fromMail:
      addr: 1953745128@qq.com          
          